# Generated by Django 3.1.3 on 2020-11-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201128_1557'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_cats',
            field=models.ManyToManyField(blank=True, to='news.Category', verbose_name='favourite categories'),
        ),
    ]
